name: check_syntax

on:
  push:
    branches:
      - main

jobs:
  check_syntax:
    name: Check Python Syntax
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Set up Python "${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install flake8
        run: |
          python -m pip install flake8
      - name: Display Python version
        run: python --version

      - name: Run flake8
        run: |
          python -m flake8
